mb/clevo/tgl-u/mainboard.c: disable AER for SSD RP
Dasharo/coreboot pull request #138
Opened 2022-03-31 12:13 UTC by mkopec

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

2022-03-31 20:45 UTC, miczyg1 commented
The question I haven't heard an answer to yet:
Does vendor FW disable AER for CPU PCIe device for all disks?

2022-03-31 20:46 UTC, miczyg1 requested changes

2022-04-01 11:50 UTC, mkopec commented
@miczyg1 I can confirm AER is also disabled when Samsung 980 PRO (a disk with no sleep-related issues) is used.

2022-04-01 15:40 UTC, miczyg1 approved these changes

2022-04-01 15:40 UTC, merged