configs/config.novacustom_nx5x: bump version to v1.3.0
Dasharo/coreboot pull request #224
Opened 2022-08-19 15:15 UTC by mkopec

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

2022-08-22 14:48 UTC, miczyg1 requested changes

2022-08-22 14:48 UTC, miczyg1 commented on src/mainboard/clevo/tgl-u/Kconfig
> +    select EC_SYSTEM76_EC_BAT_THRESHOLDS
Bad indent

2022-08-22 15:34 UTC, mkopec commented on src/mainboard/clevo/tgl-u/Kconfig
> +    select EC_SYSTEM76_EC_BAT_THRESHOLDS
Fixed

2022-08-22 17:41 UTC, mkopec commented
@miczyg1 @macpijan ping

2022-08-23 10:24 UTC, miczyg1 approved these changes

2022-08-23 10:26 UTC, merged