Protectli vault ehl fsp
Dasharo/coreboot pull request #252
Opened 2022-10-28 07:13 UTC by Stojek139808

2022-10-28 08:42 UTC, miczyg1 requested changes

2022-10-28 08:42 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +}
These are needed only for LPDDR memory. We do not set them for DIMM modules.
Take a look at CML board what is being done for DDR4 https://github.com/coreboot/coreboot/blob/master/src/mainboard/msi/ms7d25/romstage_fsp_params.c

2022-10-31 10:53 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
We configure pads in bootblock aren't we? We don't need to repeat it here.

2022-10-31 11:10 UTC, miczyg1 requested changes

2022-10-31 11:10 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +	.UserBd = BOARD_TYPE_DESKTOP, /* FIXME */
```suggestion
	.UserBd = BOARD_TYPE_DESKTOP,
```

Yes, this is the only good option here.

2022-10-31 11:10 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +	.vref_ca_config = 0x0,
```suggestion
	.vref_ca_config = 0x2,
```

This must be 2 for DDR4 DIMM boards

2022-10-31 11:10 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +	.ect = 0x0,
```suggestion
	.ect = 0x1,
```

Better enable it, because it can make more memory modules working. Saw that on MSI DDR5 board.

2022-10-31 11:10 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +#include <assert.h>
```suggestion
```
Not used

2022-10-31 11:10 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +#include <fsp/api.h>
Do we need this one?

2022-10-31 11:10 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +#include "gpio.h"
```suggestion
```
To be removed, we initialize GPIO in bootblock right?

2022-10-31 11:10 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
```suggestion
```
We configure pads in bootblock aren't we? We don't need to repeat it here.

2022-10-31 12:08 UTC, Stojek139808 commented on src/mainboard/protectli/vault_ehl/romstage.c
> +#include <fsp/api.h>
Cleaned up the headers, now its only:
```
#include <soc/romstage.h>
#include <soc/meminit.h>
```

2022-10-31 12:14 UTC, miczyg1 approved these changes

2022-10-31 12:14 UTC, merged