Protectli vault ehl/vboot
Dasharo/coreboot pull request #262
Opened 2022-11-10 08:56 UTC by Stojek139808

2022-11-14 15:59 UTC, miczyg1 requested changes

2022-11-14 16:00 UTC, miczyg1 commented
@Stojek139808 layout looks good, do you any issues?

2022-11-16 06:32 UTC, Stojek139808 commented
@miczyg1 I was just wondering if we need to add an `unused` region. I had to do that last time when making a flash map, but there the flash had 32MB.

2022-11-22 15:10 UTC, miczyg1 commented
> @miczyg1 I was just wondering if we need to add an `unused` region. I had to do that last time when making a flash map, but there the flash had 32MB.

for 16MB we do not need any unused regions and gaps.

2022-11-23 09:49 UTC, Stojek139808 commented on src/mainboard/protectli/vault_ehl/Kconfig
> +	select VBOOT_NO_BOARD_SUPPORT
Added `VBOOT_NO_TPM`, also added VBNV options that were in soc/ for elkhartlake, but are not there on this branch.

2022-11-24 10:18 UTC, miczyg1 commented on src/mainboard/protectli/vault_ehl/Kconfig
> +	select VBOOT_NO_BOARD_SUPPORT
If the SOC doesn;t select those:
```
	select VBOOT_VBNV_CMOS
	select VBOOT_VBNV_CMOS_BACKUP_TO_FLASH
```

We don't have to select it either. We may simply select `VBOOT_VBNV_FLASH` for example and get rid of the CMOS which is troublesome.

2022-11-24 10:28 UTC, Stojek139808 commented on src/mainboard/protectli/vault_ehl/Kconfig
> +	select VBOOT_NO_BOARD_SUPPORT
Fair enough, this builds too with just `VBOOT_VBNV_FLASH`, so pushed the change

2022-11-24 11:45 UTC, miczyg1 approved these changes

2022-11-24 11:45 UTC, merged