nv4x: enable dma protection
Dasharo/coreboot pull request #291
Opened 2023-02-02 14:01 UTC by Stojek139808

2023-02-22 14:23 UTC, miczyg1 requested changes

2023-02-23 12:25 UTC, Stojek139808 commented on src/soc/intel/alderlake/romstage/fsp_params.c
> +	m_cfg->PreBootDmaMask = CONFIG(ENABLE_EARLY_DMA_PROTECTION);
Done.

2023-02-23 12:26 UTC, Stojek139808 commented on src/soc/intel/alderlake/Kconfig
> +	select SOC_INTEL_COMMON_BLOCK_VTD
Done.

2023-02-23 12:26 UTC, Stojek139808 commented on src/soc/intel/alderlake/romstage/romstage.c
> +	if (CONFIG(ENABLE_EARLY_DMA_PROTECTION))
Done.

2023-03-02 12:15 UTC, miczyg1 requested changes

2023-03-02 12:15 UTC, miczyg1 commented on configs/config.novacustom_nv4x_tgl_full
> +CONFIG_DRIVERS_EFI_VARIABLE_STORE=y
Full build does not enable DMA protection? I think it should. Same for adl

2023-03-02 12:25 UTC, miczyg1 commented
@Stojek139808 I think you need to rebase because conflicts on config files appeared.

2023-03-02 12:25 UTC, miczyg1 approved these changes

2023-03-02 12:41 UTC, miczyg1 approved these changes

2023-03-02 12:41 UTC, merged