Protectli vault cml: usb stack enable
Dasharo/coreboot pull request #328
Opened 2023-03-20 12:48 UTC by Stojek139808

2023-03-20 14:07 UTC, miczyg1 requested changes

2023-03-20 14:07 UTC, miczyg1 commented on configs/config.protectli_cml_vp4630_vp4650
> +CONFIG_EDK2_TAG_OR_REV="bd421b40a9fcdb139df77e2ab583bf7de2ceae74"
VP2420 used c959ce8d30fc98b4d2dd56688580ba5e4a3290bd in the respective PR, why this is different here?

2023-03-27 13:31 UTC, Stojek139808 commented on payloads/external/edk2/Makefile
> +#BUILD_STR += --pcd gUefiPayloadPkgTokenSpaceGuid.PcdiPXEOptionName=L"$(CONFIG_EDK2_IPXE_OPTION_NAME)"
Fixed that and in general cleaned up the commits.
This was commited when I was just trying to compile edk2 from master branch and forgot to uncomment these lines.

2023-03-27 14:02 UTC, miczyg1 commented on payloads/external/edk2/Makefile
> +# DASHARO_USB_CONFIG	= FALSE
```suggestion
```

These are used for defines, not PCDs

2023-03-27 14:03 UTC, merged