Traverse PCIe topology to find optimal Max Payload Size
Dasharo/coreboot pull request #371
Opened 2023-08-18 10:20 UTC by miczyg1

Dmesg before:

```
[    2.144436] pci 0000:00:1c.0: PCI bridge to [bus 01-06]                                                                                                                                                                                     
[    2.152334] pci 0000:00:1c.0:   bridge window [mem 0x91000000-0x917fffff]                                                                                                                                                                   
[    2.156400] pci 0000:02:00.0: [1b21:1806] type 01 class 0x060400                                                                                                                                                                            
[    2.164395] pci 0000:02:00.0: Max Payload Size set to 128 (was 512, max 512)                                                                                                                                                                
[    2.172334] pci 0000:02:00.0: enabling Extended Tags                                                                                                                                                                                        
[    2.176425] pci 0000:02:00.0: PME# supported from D0 D3hot D3cold                                                                                                                                                                           
[    2.180528] pci 0000:02:02.0: [1b21:1806] type 01 class 0x060400                                                                                                                                                                            
[    2.188395] pci 0000:02:02.0: Max Payload Size set to 128 (was 512, max 512)                                                                                                                                                                
[    2.196332] pci 0000:02:02.0: enabling Extended Tags                                                                                                                                                                                        
[    2.200425] pci 0000:02:02.0: PME# supported from D0 D3hot D3cold                                                                                                                                                                           
[    2.204519] pci 0000:02:06.0: [1b21:1806] type 01 class 0x060400                                                                                                                                                                            
[    2.212395] pci 0000:02:06.0: Max Payload Size set to 128 (was 512, max 512)                                                                                                                                                                
[    2.220332] pci 0000:02:06.0: enabling Extended Tags                                                                                                                                                                                        
[    2.224425] pci 0000:02:06.0: PME# supported from D0 D3hot D3cold                                                                                                                                                                           
[    2.232520] pci 0000:02:0e.0: [1b21:1806] type 01 class 0x060400                                                                                                                                                                            
[    2.236395] pci 0000:02:0e.0: Max Payload Size set to 128 (was 512, max 512)                                                                                                                                                                
[    2.244332] pci 0000:02:0e.0: enabling Extended Tags                                                                                                                                                                                        
[    2.248435] pci 0000:02:0e.0: PME# supported from D0 D3hot D3cold                                                                                                                                                                           
[    2.256522] pci 0000:01:00.0: PCI bridge to [bus 02-06]                                                                                                                                                                                     
[    2.260338] pci 0000:01:00.0:   bridge window [mem 0x91000000-0x917fffff]                                                                                                                                                                   
[    2.268437] pci 0000:03:00.0: [8086:15f3] type 00 class 0x020000                                                                                                                                                                            
[    2.272372] pci 0000:03:00.0: reg 0x10: [mem 0x91000000-0x910fffff]                                                                                                                                                                         
[    2.280387] pci 0000:03:00.0: reg 0x1c: [mem 0x91100000-0x91103fff]                                                                                                                                                                         
[    2.284399] pci 0000:03:00.0: Max Payload Size set to 128 (was 512, max 512)                                                                                                                                                                
[    2.292473] pci 0000:03:00.0: PME# supported from D0 D3hot D3cold                                                                                                                                                                           
[    2.300612] pci 0000:02:00.0: PCI bridge to [bus 03]                                                                                                                                                                                        
[    2.304338] pci 0000:02:00.0:   bridge window [mem 0x91000000-0x911fffff]                                                                                                                                                                   
[    2.312436] pci 0000:04:00.0: [8086:15f3] type 00 class 0x020000                                                                                                                                                                            
[    2.316371] pci 0000:04:00.0: reg 0x10: [mem 0x91200000-0x912fffff]                                                                                                                                                                         
[    2.324387] pci 0000:04:00.0: reg 0x1c: [mem 0x91300000-0x91303fff]                                                                                                                                                                         
[    2.328399] pci 0000:04:00.0: Max Payload Size set to 128 (was 512, max 512)                                                                                                                                                                
[    2.336472] pci 0000:04:00.0: PME# supported from D0 D3hot D3cold                                                                                                                                                                           
[    2.344609] pci 0000:02:02.0: PCI bridge to [bus 04]                                                                                                                                                                                        
[    2.348338] pci 0000:02:02.0:   bridge window [mem 0x91200 [...]

2023-08-18 10:32 UTC, miczyg1 commented
```
iPXE> dhcp net0
Configuring (net0 00:e0:8c:b5:d1:bd)...... ok
```

iPXE also works

2023-08-18 10:33 UTC, miczyg1 commented
The PR also fixes PCIe RP2 which should be enabled for 4-port platform, otherwise only 3 NICs are present.

2023-08-18 11:17 UTC, mkopec requested changes
One typo :)

2023-08-18 11:17 UTC, mkopec commented on src/mainboard/protectli/vault_jsl/mainboard.c
> +	/* Set Max Paylaod to 256B */
```suggestion
	/* Set Max Payload to 256B */
```

2023-08-18 13:16 UTC, miczyg1 commented
> One typo :)

Done

2023-08-21 09:53 UTC, macpijan commented
@miczyg1 Is it expected that CI fails?
@mkopec Please approve if no more comments.

2023-08-21 10:08 UTC, mkopec approved these changes

2023-08-21 10:18 UTC, miczyg1 commented
> @miczyg1 Is it expected that CI fails? @mkopec Please approve if no more comments.

CI fails because a PR to protectli-blobs awaits for your approval.

2023-08-21 10:41 UTC, macpijan commented
@miczyg1 PR do blobs has been merged

2023-08-21 11:22 UTC, miczyg1 commented
> @miczyg1 PR to blobs has been merged. Do we need to adjust some code, or just re-run the job? I have just restarted it,

Rerunning will suffice. Now all checks pass.

2023-08-21 11:23 UTC, merged