Mtl h dgpu
Dasharo/coreboot pull request #548
Opened 2024-08-12 13:51 UTC by mkopec

2024-08-14 14:16 UTC, mkopec commented on src/mainboard/google/brox/acpi/power.asl
> -	/* Ramp up 1.2V rail on boards with support */
whoopsie

2024-09-11 13:39 UTC, miczyg1 commented
@mkopec something wrong happened, because the PR contains changes from iGPU variant

2024-09-11 14:04 UTC, mkopec commented
@miczyg1 rebased, should be okay now

2024-09-12 10:21 UTC, miczyg1 reviewed
Not sure how useful these comments will be. Without a spec it is hard to say what should be done and how. There is a lot of other things in original firmware ACPI. Leaving it a sa comment rather than change request,

2024-09-17 13:25 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/gps.asl
> +			CreateField (Arg1, 0, 4, QUTY)	 /* Query type */
Original firmware has all functions in the GPU's _DSM method, here we have a separate method for each function and call GPS(Arg2, Arg3) in the _DSM

2024-09-17 15:40 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/nvjt.asl
> +				(0 << 15) |		/* GC6 Version (GC6-E) */
Changed to 0x2 as in original fw

2024-09-17 15:41 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/nvjt.asl
> +				(1 << JT_FUNC_PLATPOLICY)))
yep, removed

2024-09-17 15:41 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/nvpcf.asl
> +				/* System Controller Table Header (v2.2), 1 controller entry */
Changed to 2.4 in https://github.com/Dasharo/coreboot/pull/548/commits/950f78bdbfaa995ac71ff9a140d9469c6d9f253f

2024-09-17 15:41 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/nvpcf.asl
> +				0x22, 0x05, 0x10, 0x1c, 0x01 }
Changed to 2.4 in https://github.com/Dasharo/coreboot/pull/548/commits/950f78bdbfaa995ac71ff9a140d9469c6d9f253f

2024-09-17 15:41 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/nvpcf.asl
> +				0x00, 0x00, 0x00, 0x00,
Changed to 0x1 in https://github.com/Dasharo/coreboot/pull/548/commits/950f78bdbfaa995ac71ff9a140d9469c6d9f253f

2024-10-02 14:36 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/gps.asl
> +CreateDWordField (GPSP, 8, TGPU)
Yes, but it doesn't actually populate most of them. Tested by calling the DSM by acpidbg, we should now be returning the same exact values

2024-10-02 14:36 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/nvop.asl
> +				(0 << 6) |	/* Shared Discrete GPU Hotplug Capabilities */
yes, fixed in https://github.com/Dasharo/coreboot/pull/548/commits/554b771a19486fb4979cdfc84fe57ac18600f291

2024-10-29 11:48 UTC, mkopec commented on src/mainboard/clevo/mtl-h/acpi/dgpu/gpu_top.asl
> +		Method (DNOT, 2, Serialized)
It's now used: https://github.com/Dasharo/coreboot/pull/548/commits/bab51b072f04e36df4db7cbeca4f09e4723dd1fd

2024-11-13 10:10 UTC, miczyg1 requested changes

2024-11-13 10:10 UTC, miczyg1 commented on .github/workflows/build.yml
> -  build_novacustom_ec:
@mkopec I think we can still build EC regardless if EC sync is used or not. The "Obtain EC" step is removed and the dependency too, so it should be fine.

2024-11-18 16:42 UTC, mkopec commented on .github/workflows/build.yml
> -  build_novacustom_ec:
Right, commit amended: https://github.com/Dasharo/coreboot/commit/c2b15730096a54a4518709d9390e66fa8d58acea

2024-11-19 12:58 UTC, miczyg1 approved these changes

2024-11-19 13:01 UTC, merged