Protectli adl ppi
Dasharo/coreboot pull request #604
Opened 2024-12-12 15:05 UTC by miczyg1

2024-12-13 11:38 UTC, mkopec approved these changes, later dismissed

2024-12-13 14:50 UTC, SergiiDmytruk requested changes
Typos.  The problematic one is in `payloads/external/edk2/Makefile`.

2024-12-13 14:50 UTC, SergiiDmytruk commented on payloads/external/edk2/Kconfig.dasharo
> +	  fro platform-specific issues causing the RAM to not  be preserved
Typos:
```suggestion
	  Tell UEFIPaylaod to use TPM PPI buffer in UEFI variables. Workaround
	  for platform-specific issues causing the RAM to not be preserved
```

2024-12-13 14:50 UTC, SergiiDmytruk commented on payloads/external/edk2/Makefile
> +ifeq ($(COFNIG_EDK2_USE_UEFIVAR_BACKED_TPM_PPI),y)
```suggestion
ifeq ($(CONFIG_EDK2_USE_UEFIVAR_BACKED_TPM_PPI),y)
```

2024-12-16 09:15 UTC, miczyg1 commented
https://github.com/Dasharo/coreboot/pull/604/commits/17897d437676f51e7f6cf19c9092a712c03fcce1 squashed into
https://github.com/Dasharo/coreboot/pull/604/commits/4831c0d23646891c57bfdbed9b3a140eefa0c2d7 for clean history.

2024-12-16 11:54 UTC, mkopec commented on payloads/external/edk2/Kconfig.dasharo
> +	  Tell UEFIPaylaod to use TPM PPI buffer in UEFI variables. Workaround
```suggestion
	help
	  Tell UEFIPayload to use TPM PPI buffer in UEFI variables. Workaround
```

2024-12-16 16:47 UTC, miczyg1 commented on payloads/external/edk2/Kconfig.dasharo
> +	  Tell UEFIPaylaod to use TPM PPI buffer in UEFI variables. Workaround
https://github.com/Dasharo/coreboot/compare/349b75f1cc3ad96b1a8c2638b4e170272282bef0..dac568f4e6b5a9d0cce28b5be53f7d2b0acbac15

2024-12-16 18:00 UTC, SergiiDmytruk approved these changes

2024-12-17 09:09 UTC, merged